Modifications to let ist run with patched 2.6 kernel. Pure 2.6.0/2.6.1 is not working.

diff --git a/capiinit/configure b/capiinit/configure
--- a/capiinit/configure
+++ b/capiinit/configure
@@ -1285,7 +1285,7 @@ EOF
  
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: "Missing $ac_hdr. Kernel source installed?"" 1>&2; exit 1; }
+{ echo "configure: error: Missing $ac_hdr. Kernel source installed?" 1>&2; exit 1; }
 fi
 done
 
