Please see CHANGES for a detailed description

diff --git a/vbox/utils/mkdoc b/vbox/utils/mkdoc
--- a/vbox/utils/mkdoc
+++ b/vbox/utils/mkdoc
@@ -1,35 +1,34 @@
 #! /bin/sh
 ##
-## $Id#
+## $Id: mkdoc,v 1.2 1997/04/28 16:52:25 michael Exp $
 ##
 ## Create the documents from sgml source. Please *only* call this
 ## script from top level makefile!
 
-SGML2TEXT="/usr/local/lib/linuxdoc-sgml/bin/sgml2txt"
-SGML2HTML="/usr/local/lib/linuxdoc-sgml/bin/sgml2html"
+cd "$1"
 
-DOCLANGS="de"
+if [ "$?" != "0" ]
+then
+	echo "ERROR: Can't change to directory '$1'..."
+        exit 5
+fi
 
-for l in ${DOCLANGS}
-do
-   cd "${VBOX_TOPDIR}/doc/${l}"
+echo -n "$1: "
 
-   ${SGML2TEXT} -l -f vbox
+sgml2txt -l vbox.sgml.in
 
-   if [ "$l" = "de" ]
-   then
-      ${SGML2HTML} -l -L deutsch vbox
-   else
-      ${SGML2HTML} -l vbox
-   fi
+if [ "$?" = "0" ]
+then
+	mv vbox.sgml.in.txt vbox.txt.in
 
-   for i in *.html
-   do
-     mv $i html/$i.in
-   done
+	if [ "$?" != "0" ]
+	then
+		echo "ERROR: Can't move '$1/vbox.sgml.in.txt' to '$1/vbox.txt.in'."
+		exit 5
+	fi
+else
+	echo "ERROR: Can't create '$1/vbox.sgml.in.txt'."
+	exit 5
+fi
 
-   for i in *.txt
-   do
-      mv $i txt/$i.in
-   done
-done
+exit 0
